"""Initial migration

Revision ID: 7ac6ae06dd54
Revises: 
Create Date: 2025-05-26 21:09:46.730271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac6ae06dd54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_session_duration', sa.Integer(), nullable=True),
    sa.Column('break_duration', sa.Integer(), nullable=True),
    sa.Column('focus_threshold', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('study_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('planned_duration', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_focus_time', sa.Integer(), nullable=True),
    sa.Column('total_distraction_time', sa.Integer(), nullable=True),
    sa.Column('focus_percentage', sa.Float(), nullable=True),
    sa.Column('average_attention_score', sa.Float(), nullable=True),
    sa.Column('break_count', sa.Integer(), nullable=True),
    sa.Column('total_break_time', sa.Integer(), nullable=True),
    sa.Column('blink_rate', sa.Float(), nullable=True),
    sa.Column('posture_score', sa.Float(), nullable=True),
    sa.Column('fatigue_level', sa.Float(), nullable=True),
    sa.Column('eye_tracking_enabled', sa.Boolean(), nullable=True),
    sa.Column('break_reminders_enabled', sa.Boolean(), nullable=True),
    sa.Column('posture_monitoring_enabled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_analytics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_study_time', sa.Integer(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('average_focus_percentage', sa.Float(), nullable=True),
    sa.Column('average_attention_score', sa.Float(), nullable=True),
    sa.Column('completed_sessions', sa.Integer(), nullable=True),
    sa.Column('cancelled_sessions', sa.Integer(), nullable=True),
    sa.Column('total_breaks', sa.Integer(), nullable=True),
    sa.Column('average_session_duration', sa.Float(), nullable=True),
    sa.Column('average_blink_rate', sa.Float(), nullable=True),
    sa.Column('average_posture_score', sa.Float(), nullable=True),
    sa.Column('average_fatigue_level', sa.Float(), nullable=True),
    sa.Column('total_distractions', sa.Integer(), nullable=True),
    sa.Column('productivity_score', sa.Float(), nullable=True),
    sa.Column('focus_streak_minutes', sa.Integer(), nullable=True),
    sa.Column('best_focus_time_start', sa.Time(), nullable=True),
    sa.Column('best_focus_time_end', sa.Time(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eye_tracking_data',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('left_eye_x', sa.Float(), nullable=True),
    sa.Column('left_eye_y', sa.Float(), nullable=True),
    sa.Column('right_eye_x', sa.Float(), nullable=True),
    sa.Column('right_eye_y', sa.Float(), nullable=True),
    sa.Column('gaze_x', sa.Float(), nullable=True),
    sa.Column('gaze_y', sa.Float(), nullable=True),
    sa.Column('gaze_direction', sa.String(length=20), nullable=True),
    sa.Column('attention_score', sa.Float(), nullable=True),
    sa.Column('is_focused', sa.Boolean(), nullable=True),
    sa.Column('distraction_type', sa.String(length=50), nullable=True),
    sa.Column('is_blinking', sa.Boolean(), nullable=True),
    sa.Column('blink_duration', sa.Float(), nullable=True),
    sa.Column('head_pitch', sa.Float(), nullable=True),
    sa.Column('head_yaw', sa.Float(), nullable=True),
    sa.Column('head_roll', sa.Float(), nullable=True),
    sa.Column('distance_cm', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eye_tracking_data')
    op.drop_table('user_analytics')
    op.drop_table('study_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
